### PR TITLE
Updated pysnmp to 4.3.5

### LINKED ISSUE #36: Starting mkeventd with --snmptrap gives error
/usr/bin/python /omd/sites/testsite/bin/mkeventd  --snmptrap
FATAL ERROR: No module named rfc1902

### PR DESCRIPTION
**Pull request by firegore**
Needed for mkeventd --snmptrap Support
Fixes #36

### CODE REVIEW

**Comment by sni** [comment]
Its not so easy. The new pysnmp version requires more dependencies than the old one. In my testbuild it had to install: pycryptodome, pysmi, pyasn1 and ply.

**Comment by firegore** [comment]
Only pyasn1 is needed as dependency, the other ones are optional
See: [http://pysnmp.sourceforge.net/download.html](http://pysnmp.sourceforge.net/download.html)

Is there a special way to also add pyasn1, or just same procedure as with the other Python Modules? (i.e. Tarball and Entry in the Makefile)

**Comment by sni** [comment]
Right, just add the tarball and the entry in the Makefile before pysnmp.  Then we just need to find out how to run setup.py without the optional dependencies.

**Comment by firegore** [comment]
I've also looked through the MKEventd Code and it looks like that only pysnmp and pyasn1 are used

**Comment by firegore** [comment]
The Requirements are listed in the requirements.txt the optionals are also listed.

I see 3 ways to solve this:
Pre-Modify the pysnmp-4.3.5.tar.gz  requirements.txt and delete the optional dependencies
Add a ".patch logic" in the PythonModules Makefile (like on the naemon-livestatus Package)
Or just also install the optional dependencies, would be only 3 Packages more.

**Comment by firegore** [comment]
Im just gonna add all the Dependencies, that looks like the cleanest Way to do this.

Pre-modifying the Tarball doesn't seem like a good Idea.

**Comment by sni** [comment]
ply and pysmi are missing in the makefile, besides that, yes, a few more modules sounds better than modifing existing tarballs.

**Comment by firegore** [comment]
Thanks for the Heads-up, i resetted the Makefile commit and forgot afterwards to add them back

**Comment by sni** [comment]
Merged, thanks.

**Pull request closed without merging**
