### PR TITLE
Add gearman_top alias to environment

### PR DESCRIPTION
**Pull request by jstark1**
with this gearman_top alias is the site specific port "preconfigured"

### CODE REVIEW

**Comment by sni** [comment]
This should not be neccessary since https://github.com/sni/mod_gearman/commit/3c9816228915c2d9972977827a6bd1263e64b8b2
gearman_top automatically reads the env variable CONFIG_GEARMAND_PORT which contains host and port in omd.
This has been release with gearman_top v3.3.2

**Comment by jstark1** [comment]
ok interesting. we are currently on omd 3.30. 4.00 ships a supported version. Then we must set the variable like this:

```
export CONFIG_GEARMAND_PORT=127.0.0.1:`omd config show |grep GEARMAND_PORT | cut -f 3 -d ":"`
```

**Comment by sni** [comment]
all config variables are exported automatically through: etc/profile.d/omd_export_site_conf.sh which is sourced from the .profile

**Comment by jstark1** [comment]
Perfect. thank for the clarification

**Pull request closed without merging**
